Add one missing patch to support FreeBSD
First I thought this change is unnecessary because there is not update service provided for FreeBSD. However, without this change code-oss does not start with error:
Error: [invokeFunction] unknown service 'updateService'